import { useState } from 'react'
import { useSaveAdminImageMutation, useSaveAdminPlanMutation } from '@/services/cloudApi'

export function CatalogEditor() {
  const [imageName,setImageName]=useState('');const [imageRef,setImageRef]=useState('');const [planName,setPlanName]=useState('');const [cpu,setCPU]=useState(2);const [memory,setMemory]=useState(4096);const [price,setPrice]=useState(9900);const [error,setError]=useState('')
  const [saveImage,{isLoading:imageSaving}]=useSaveAdminImageMutation();const [savePlan,{isLoading:planSaving}]=useSaveAdminPlanMutation()
  async function addImage(){try{setError('');await saveImage({id:'',name:imageName,imageRef,imageDigest:'',version:'latest',enabled:true}).unwrap();setImageName('');setImageRef('')}catch{setError('镜像来源保存失败，请确认镜像地址') }}
  async function addPlan(){try{setError('');await savePlan({id:'',name:planName,cpu,memoryMB:memory,monthlyPriceFen:price,enabled:true,sortOrder:100}).unwrap();setPlanName('')}catch{setError('套餐保存失败') }}
  return <div className="summary admin-editor catalog-editor"><h3>新增可售商品</h3><p>只维护可信镜像来源。用户默认使用 latest，也可选择该来源下的其他版本。</p><label htmlFor="catalog-name">镜像名称</label><input id="catalog-name" value={imageName} onChange={event=>setImageName(event.target.value)} placeholder="AlemonX"/><label htmlFor="catalog-ref">镜像地址</label><input id="catalog-ref" value={imageRef} onChange={event=>setImageRef(event.target.value)} placeholder="registry.example/alemonx"/><button className="primary" disabled={imageSaving||!imageName||!imageRef} onClick={()=>void addImage()}>{imageSaving?'正在保存…':'新增镜像来源'}</button><label htmlFor="catalog-plan">套餐名称</label><input id="catalog-plan" value={planName} onChange={event=>setPlanName(event.target.value)} placeholder="标准版"/><label htmlFor="catalog-cpu">CPU 核数</label><input id="catalog-cpu" type="number" min="1" value={cpu} onChange={event=>setCPU(Number(event.target.value))}/><label htmlFor="catalog-memory">内存 MB</label><input id="catalog-memory" type="number" min="256" value={memory} onChange={event=>setMemory(Number(event.target.value))}/><label htmlFor="catalog-price">月价（分）</label><input id="catalog-price" type="number" min="0" value={price} onChange={event=>setPrice(Number(event.target.value))}/><button className="primary" disabled={planSaving||!planName} onClick={()=>void addPlan()}>{planSaving?'正在保存…':'新增套餐'}</button>{error&&<p className="login-error" role="alert">{error}</p>}</div>
}
