import { useEffect, useState } from 'react'
import { useSaveAdminNodeMutation } from '@/services/cloudApi'
import type { Node } from '@/types/cloud'

export function NodeEditor({ nodes }: { nodes: Node[] }) {
  const [selected,setSelected]=useState<Node>();const [cpu,setCPU]=useState(0);const [memory,setMemory]=useState(0);const [agentURL,setAgentURL]=useState('');const [enabled,setEnabled]=useState(true);const [error,setError]=useState('');const [newName,setNewName]=useState('');const [newURL,setNewURL]=useState('');const [newToken,setNewToken]=useState('');const [newCPU,setNewCPU]=useState(16);const [newMemory,setNewMemory]=useState(262144);const [save,{isLoading}]=useSaveAdminNodeMutation()
  useEffect(()=>{const node=nodes[0];if(node&&!selected){setSelected(node);setCPU(node.cpuTotal);setMemory(node.memoryTotalMB);setAgentURL(node.agentURL);setEnabled(node.enabled)}},[nodes,selected])
  async function submit(){if(!selected)return;try{setError('');await save({...selected,cpuTotal:cpu,memoryTotalMB:memory,agentURL,enabled}).unwrap()}catch{setError('节点配置保存失败') }}
  async function register(){try{setError('');await save({id:'',name:newName,agentURL:newURL,agentToken:newToken,cpuTotal:newCPU,memoryTotalMB:newMemory,cpuReserved:0,memoryReservedMB:0,enabled:true}).unwrap();setNewName('');setNewURL('');setNewToken('')}catch{setError('Agent 验证失败或节点保存失败') }}
  return <div className="summary admin-editor node-editor">{selected&&<><h3>节点配置</h3><label htmlFor="node-select">节点</label><select id="node-select" value={selected.id} onChange={event=>{const node=nodes.find(value=>value.id===event.target.value);if(node){setSelected(node);setCPU(node.cpuTotal);setMemory(node.memoryTotalMB);setAgentURL(node.agentURL);setEnabled(node.enabled)}}}>{nodes.map(node=><option key={node.id} value={node.id}>{node.name}</option>)}</select><label htmlFor="node-agent">Agent 内网地址</label><input id="node-agent" value={agentURL} onChange={event=>setAgentURL(event.target.value)} /><label htmlFor="node-cpu">总 CPU 核数</label><input id="node-cpu" type="number" min="1" value={cpu} onChange={event=>setCPU(Number(event.target.value))}/><label htmlFor="node-memory">总内存 MB</label><input id="node-memory" type="number" min="256" value={memory} onChange={event=>setMemory(Number(event.target.value))}/><label htmlFor="node-enabled">节点状态</label><select id="node-enabled" value={enabled?'enabled':'disabled'} onChange={event=>setEnabled(event.target.value==='enabled')}><option value="enabled">启用</option><option value="disabled">停用</option></select><button className="primary" disabled={isLoading||cpu<=0||memory<256} onClick={()=>void submit()}>{isLoading?'正在保存…':'保存节点配置'}</button></>}<hr/><h3>注册新节点</h3><label>节点名称<input value={newName} onChange={event=>setNewName(event.target.value)} /></label><label>Agent 内网地址<input value={newURL} onChange={event=>setNewURL(event.target.value)} placeholder="http://10.0.0.12:13092" /></label><label>一次性 Agent 令牌<input type="password" value={newToken} onChange={event=>setNewToken(event.target.value)} autoComplete="new-password" /></label><label>CPU 核数<input type="number" min="1" value={newCPU} onChange={event=>setNewCPU(Number(event.target.value))} /></label><label>内存 MB<input type="number" min="256" value={newMemory} onChange={event=>setNewMemory(Number(event.target.value))} /></label><button className="primary" disabled={isLoading||!newName.trim()||!newURL.trim()||!newToken.trim()} onClick={()=>void register()}>{isLoading?'正在验证…':'验证并注册节点'}</button>{error&&<p className="login-error" role="alert">{error}</p>}</div>
}
