import { useState } from 'react'
import { useCreateInstanceMutation } from '@/services/cloudApi'
import type { Instance, Page } from '@/types/cloud'
const images = ['ccr.ccs.tencentyun.com/ningmengchongshui/alemonx', 'alemonx/alemonx:latest']
const versions = ['latest', 'v2.4.1', 'v2.3.8']
const specs = [{ cpu: 2, memoryMB: 4096 }, { cpu: 4, memoryMB: 8192 }, { cpu: 8, memoryMB: 16384 }]
export function DashboardPage({ instances, loading, page, onCreate, onCreated }: { instances: Instance[]; loading: boolean; page: Page; onCreate: () => void; onCreated: () => void }) {
  const [name, setName] = useState('alemonx-production'); const [image, setImage] = useState(images[0]); const [version, setVersion] = useState(versions[0]); const [specIndex, setSpecIndex] = useState(1); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const [createInstance] = useCreateInstanceMutation()
  if (page === 'create') { const spec = specs[specIndex]; return <section className="page"><header><div><p className="eyebrow">部署向导</p><h1>创建 AlemonX</h1><p>容器仅通过专属域名在内部网络中访问，不开放宿主机端口。</p></div></header><div className="summary"><label htmlFor="name">实例名称</label><input id="name" value={name} maxLength={48} onChange={e => setName(e.target.value)} /><label htmlFor="image">镜像地址</label><select id="image" value={image} onChange={e => setImage(e.target.value)}>{images.map(value => <option key={value} value={value}>{value}</option>)}</select><label htmlFor="version">版本</label><select id="version" value={version} onChange={e => setVersion(e.target.value)}>{versions.map(value => <option key={value}>{value}</option>)}</select><label htmlFor="spec">计算规格</label><select id="spec" value={specIndex} onChange={e => setSpecIndex(Number(e.target.value))}>{specs.map((value, index) => <option key={value.cpu} value={index}>{value.cpu} 核 / {value.memoryMB / 1024} GB</option>)}</select>{error && <p className="login-error" role="alert">{error}</p>}<button className="primary full" disabled={saving || !name.trim()} onClick={() => { setSaving(true); setError(''); void createInstance({ name: name.trim(), image, version, cpu: spec.cpu, memoryMB: spec.memoryMB, spec: `${spec.cpu} 核 / ${spec.memoryMB / 1024} GB` }).unwrap().then(onCreated).catch(() => setError('提交失败，请稍后重试')).finally(() => setSaving(false)) }}>{saving ? '正在提交部署…' : '确认并创建'}</button></div></section> }
  if (page === 'admin') return <section className="page"><header><div><p className="eyebrow">平台运维</p><h1>超级管理台</h1><p>集中查看裸机节点、镜像仓库与用户部署情况。</p></div></header></section>
  return <section className="page"><header><div><p className="eyebrow">资源管理</p><h1>我的 AlemonX</h1><p>管理你已部署的实例。</p></div><button className="primary" onClick={onCreate}>＋ 创建 AlemonX</button></header><div className="metrics"><article className="metric"><span>实例总数</span><strong>{instances.length}</strong><small>容器按用户隔离</small></article><article className="metric"><span>访问方式</span><strong>专属域名</strong><small>不映射宿主机端口</small></article></div><div className="table-box">{loading ? <div className="empty-state">正在加载实例…</div> : instances.length === 0 ? <div className="empty-state">暂无实例，创建后将显示在这里。</div> : <table><thead><tr><th>实例名称</th><th>镜像 / 版本</th><th>配置</th><th>状态</th><th>访问</th></tr></thead><tbody>{instances.map(item => <tr key={item.id}><td>{item.name}</td><td>{item.image}<small>{item.version}</small></td><td>{item.spec}</td><td>{item.status}</td><td>{item.ip}</td></tr>)}</tbody></table>}</div></section>
}
