ALTER TABLE xcloud_instances ADD COLUMN cpu DECIMAL(8,2) NOT NULL DEFAULT 0;
ALTER TABLE xcloud_instances ADD COLUMN memory_mb INT NOT NULL DEFAULT 0;
ALTER TABLE xcloud_instances ADD COLUMN node_id VARCHAR(64) NULL;
ALTER TABLE xcloud_instances ADD COLUMN order_id VARCHAR(64) NULL;
ALTER TABLE xcloud_instances ADD COLUMN route_key VARCHAR(32) NULL;
ALTER TABLE xcloud_instances ADD COLUMN expires_at DATETIME NULL;
ALTER TABLE xcloud_instances ADD COLUMN purge_at DATETIME NULL;
ALTER TABLE xcloud_instances ADD COLUMN retention_days SMALLINT NOT NULL DEFAULT 7;
ALTER TABLE xcloud_instances ADD UNIQUE KEY uq_xcloud_route_key (route_key);
ALTER TABLE xcloud_nodes ADD COLUMN updated_at DATETIME NULL;
ALTER TABLE xcloud_nodes ADD COLUMN cpu_detected DECIMAL(8,2) NOT NULL DEFAULT 0;
ALTER TABLE xcloud_nodes ADD COLUMN memory_detected_mb INT NOT NULL DEFAULT 0;
UPDATE xcloud_nodes SET cpu_detected=cpu_total,memory_detected_mb=memory_total_mb WHERE cpu_detected=0 OR memory_detected_mb=0;
ALTER TABLE xcloud_nodes ADD COLUMN agent_token_ciphertext TEXT NULL;
ALTER TABLE xcloud_nodes ADD COLUMN docker_version VARCHAR(64) NULL;
ALTER TABLE xcloud_nodes ADD COLUMN disk_available_bytes BIGINT NULL;
ALTER TABLE xcloud_nodes ADD COLUMN managed_container_count INT NULL;
ALTER TABLE xcloud_tasks ADD COLUMN payload JSON NULL;
ALTER TABLE xcloud_tasks ADD COLUMN finished_at DATETIME NULL;
ALTER TABLE xcloud_orders ADD COLUMN renewal_instance_id VARCHAR(64) NULL;
ALTER TABLE xcloud_orders ADD COLUMN payment_source VARCHAR(32) NULL;
ALTER TABLE xcloud_orders ADD COLUMN wallet_entry_id VARCHAR(64) NULL;
ALTER TABLE xcloud_orders ADD COLUMN scheduled_node_id VARCHAR(64) NULL;
ALTER TABLE xcloud_orders ADD COLUMN selected_image_version VARCHAR(64) NULL;
ALTER TABLE xcloud_orders ADD COLUMN service_starts_at DATETIME NULL;
ALTER TABLE xcloud_orders ADD COLUMN refunded_at DATETIME NULL;
ALTER TABLE xcloud_orders ADD COLUMN refund_amount_fen INT NULL;
ALTER TABLE xcloud_orders ADD COLUMN refund_wallet_entry_id VARCHAR(64) NULL;
ALTER TABLE xcloud_orders ADD UNIQUE KEY uq_xcloud_orders_refund_entry (refund_wallet_entry_id);
ALTER TABLE xcloud_wallet_entries ADD COLUMN order_id VARCHAR(64) NULL;
ALTER TABLE xcloud_wallet_entries ADD INDEX idx_xcloud_wallet_entries_order (order_id);
ALTER TABLE xcloud_images MODIFY COLUMN image_digest VARCHAR(255) NULL;
CREATE TABLE IF NOT EXISTS xcloud_instance_notification_events (instance_id VARCHAR(64) NOT NULL, event_type VARCHAR(32) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (instance_id, event_type)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
