CREATE TABLE IF NOT EXISTS xcloud_instance_plan_changes (
  id VARCHAR(64) PRIMARY KEY,
  instance_id VARCHAR(64) NOT NULL,
  owner_id VARCHAR(191) NOT NULL,
  source_plan_id VARCHAR(64) NOT NULL,
  target_plan_id VARCHAR(64) NOT NULL,
  source_cpu DECIMAL(8,2) NOT NULL,
  source_memory_mb INT NOT NULL,
  target_cpu DECIMAL(8,2) NOT NULL,
  target_memory_mb INT NOT NULL,
  remaining_seconds BIGINT NOT NULL,
  delta_fen INT NOT NULL,
  charge_fen INT NOT NULL DEFAULT 0,
  refund_fen INT NOT NULL DEFAULT 0,
  status VARCHAR(24) NOT NULL,
  task_id VARCHAR(64) NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  pending_wallet_entry_id VARCHAR(64) NULL,
  settlement_wallet_entry_id VARCHAR(64) NULL,
  before_snapshot JSON NOT NULL,
  after_snapshot JSON NOT NULL,
  error_message TEXT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  completed_at DATETIME NULL,
  UNIQUE KEY uq_xcloud_plan_change_idempotency (idempotency_key),
  INDEX idx_xcloud_plan_changes_instance (instance_id, created_at),
  INDEX idx_xcloud_plan_changes_status (status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
